services:
  - type: web
    name: shoxrux-portfolio-server
    env: node
    rootDir: server
    buildCommand: npm install --production
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        value: https://client-dd2c.onrender.com

  # Frontend static site
  - type: static
    name: shoxrux-portfolio-client
    env: static
    rootDir: client
    buildCommand: npm install && chmod +x build.sh && ./build.sh
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://shoxrux-sssem.onrender.com
