services:
  - type: web
    name: shoxrux-portfolio-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: static
    name: shoxrux-portfolio-client
    env: static
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://shoxrux-portfolio-server.onrender.com
